// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/borrow.proto

package borrow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Borrow service

func NewBorrowEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Borrow service

type BorrowService interface {
	Borrow(ctx context.Context, in *Borrow_Request, opts ...client.CallOption) (*Response, error)
	Return(ctx context.Context, in *Returns_Request, opts ...client.CallOption) (*Response, error)
	ToOther(ctx context.Context, in *ToOtherRequest, opts ...client.CallOption) (*Response, error)
	CheckToOther(ctx context.Context, in *ToOtherRequest, opts ...client.CallOption) (*Response, error)
	FindBorrowAll(ctx context.Context, in *Null_Request, opts ...client.CallOption) (*Borrowlogs_Response, error)
	FindBorrowByID(ctx context.Context, in *ID_Request, opts ...client.CallOption) (*Borrowlog_Response, error)
	FindBorrowByWID(ctx context.Context, in *WID_Request, opts ...client.CallOption) (*Borrowlogs_Response, error)
	FindBorrowByPID(ctx context.Context, in *PID_Request, opts ...client.CallOption) (*Borrowlogs_Response, error)
}

type borrowService struct {
	c    client.Client
	name string
}

func NewBorrowService(name string, c client.Client) BorrowService {
	return &borrowService{
		c:    c,
		name: name,
	}
}

func (c *borrowService) Borrow(ctx context.Context, in *Borrow_Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.Borrow", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) Return(ctx context.Context, in *Returns_Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.Return", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) ToOther(ctx context.Context, in *ToOtherRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.ToOther", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) CheckToOther(ctx context.Context, in *ToOtherRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.CheckToOther", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) FindBorrowAll(ctx context.Context, in *Null_Request, opts ...client.CallOption) (*Borrowlogs_Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.FindBorrowAll", in)
	out := new(Borrowlogs_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) FindBorrowByID(ctx context.Context, in *ID_Request, opts ...client.CallOption) (*Borrowlog_Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.FindBorrowByID", in)
	out := new(Borrowlog_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) FindBorrowByWID(ctx context.Context, in *WID_Request, opts ...client.CallOption) (*Borrowlogs_Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.FindBorrowByWID", in)
	out := new(Borrowlogs_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowService) FindBorrowByPID(ctx context.Context, in *PID_Request, opts ...client.CallOption) (*Borrowlogs_Response, error) {
	req := c.c.NewRequest(c.name, "Borrow.FindBorrowByPID", in)
	out := new(Borrowlogs_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Borrow service

type BorrowHandler interface {
	Borrow(context.Context, *Borrow_Request, *Response) error
	Return(context.Context, *Returns_Request, *Response) error
	ToOther(context.Context, *ToOtherRequest, *Response) error
	CheckToOther(context.Context, *ToOtherRequest, *Response) error
	FindBorrowAll(context.Context, *Null_Request, *Borrowlogs_Response) error
	FindBorrowByID(context.Context, *ID_Request, *Borrowlog_Response) error
	FindBorrowByWID(context.Context, *WID_Request, *Borrowlogs_Response) error
	FindBorrowByPID(context.Context, *PID_Request, *Borrowlogs_Response) error
}

func RegisterBorrowHandler(s server.Server, hdlr BorrowHandler, opts ...server.HandlerOption) error {
	type borrow interface {
		Borrow(ctx context.Context, in *Borrow_Request, out *Response) error
		Return(ctx context.Context, in *Returns_Request, out *Response) error
		ToOther(ctx context.Context, in *ToOtherRequest, out *Response) error
		CheckToOther(ctx context.Context, in *ToOtherRequest, out *Response) error
		FindBorrowAll(ctx context.Context, in *Null_Request, out *Borrowlogs_Response) error
		FindBorrowByID(ctx context.Context, in *ID_Request, out *Borrowlog_Response) error
		FindBorrowByWID(ctx context.Context, in *WID_Request, out *Borrowlogs_Response) error
		FindBorrowByPID(ctx context.Context, in *PID_Request, out *Borrowlogs_Response) error
	}
	type Borrow struct {
		borrow
	}
	h := &borrowHandler{hdlr}
	return s.Handle(s.NewHandler(&Borrow{h}, opts...))
}

type borrowHandler struct {
	BorrowHandler
}

func (h *borrowHandler) Borrow(ctx context.Context, in *Borrow_Request, out *Response) error {
	return h.BorrowHandler.Borrow(ctx, in, out)
}

func (h *borrowHandler) Return(ctx context.Context, in *Returns_Request, out *Response) error {
	return h.BorrowHandler.Return(ctx, in, out)
}

func (h *borrowHandler) ToOther(ctx context.Context, in *ToOtherRequest, out *Response) error {
	return h.BorrowHandler.ToOther(ctx, in, out)
}

func (h *borrowHandler) CheckToOther(ctx context.Context, in *ToOtherRequest, out *Response) error {
	return h.BorrowHandler.CheckToOther(ctx, in, out)
}

func (h *borrowHandler) FindBorrowAll(ctx context.Context, in *Null_Request, out *Borrowlogs_Response) error {
	return h.BorrowHandler.FindBorrowAll(ctx, in, out)
}

func (h *borrowHandler) FindBorrowByID(ctx context.Context, in *ID_Request, out *Borrowlog_Response) error {
	return h.BorrowHandler.FindBorrowByID(ctx, in, out)
}

func (h *borrowHandler) FindBorrowByWID(ctx context.Context, in *WID_Request, out *Borrowlogs_Response) error {
	return h.BorrowHandler.FindBorrowByWID(ctx, in, out)
}

func (h *borrowHandler) FindBorrowByPID(ctx context.Context, in *PID_Request, out *Borrowlogs_Response) error {
	return h.BorrowHandler.FindBorrowByPID(ctx, in, out)
}
