// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: proto/borrow.proto

package borrow

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Borrow_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId     int64  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id"`             //借出人信息
	ProductId    int64  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id"`          //借出产品信息
	BorrowTime   int64  `protobuf:"varint,3,opt,name=borrow_time,json=borrowTime,proto3" json:"borrow_time"`       //借出时间
	ScheduleTime int64  `protobuf:"varint,4,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time"` //预计归还时间
	ReturnTime   int64  `protobuf:"varint,5,opt,name=return_time,json=returnTime,proto3" json:"return_time"`
	Description  string `protobuf:"bytes,6,opt,name=description,proto3" json:"description"` //备注信息,转借等等说明
}

func (x *Borrow_Request) Reset() {
	*x = Borrow_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrow_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrow_Request) ProtoMessage() {}

func (x *Borrow_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrow_Request.ProtoReflect.Descriptor instead.
func (*Borrow_Request) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{0}
}

func (x *Borrow_Request) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *Borrow_Request) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Borrow_Request) GetBorrowTime() int64 {
	if x != nil {
		return x.BorrowTime
	}
	return 0
}

func (x *Borrow_Request) GetScheduleTime() int64 {
	if x != nil {
		return x.ScheduleTime
	}
	return 0
}

func (x *Borrow_Request) GetReturnTime() int64 {
	if x != nil {
		return x.ReturnTime
	}
	return 0
}

func (x *Borrow_Request) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Null_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null_Request) Reset() {
	*x = Null_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null_Request) ProtoMessage() {}

func (x *Null_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null_Request.ProtoReflect.Descriptor instead.
func (*Null_Request) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{1}
}

type ID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *ID_Request) Reset() {
	*x = ID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID_Request) ProtoMessage() {}

func (x *ID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID_Request.ProtoReflect.Descriptor instead.
func (*ID_Request) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{2}
}

func (x *ID_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WID int64 `protobuf:"varint,1,opt,name=WID,proto3" json:"WID"`
}

func (x *WID_Request) Reset() {
	*x = WID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WID_Request) ProtoMessage() {}

func (x *WID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WID_Request.ProtoReflect.Descriptor instead.
func (*WID_Request) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{3}
}

func (x *WID_Request) GetWID() int64 {
	if x != nil {
		return x.WID
	}
	return 0
}

type PID_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID int64 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID"`
}

func (x *PID_Request) Reset() {
	*x = PID_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PID_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID_Request) ProtoMessage() {}

func (x *PID_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID_Request.ProtoReflect.Descriptor instead.
func (*PID_Request) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{4}
}

func (x *PID_Request) GetPID() int64 {
	if x != nil {
		return x.PID
	}
	return 0
}

type Borrowlog_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//ID int64 `gorm:"primary_key;not_null;auto_increment;" json:"ID"`
	//PID int64 `json:"pid"`//物品的id
	//WID int64 `json:"wid"`//借出员工ID
	//BorrowTime int64 `json:"borrow_time"`//出借时间
	//ScheduleTime int64 `json:"schedule_time"`//预定归还时间
	//ReturnTime int64 `json:"ReturnTime"`//实际归还时间,给0代表是借出并为归还。
	//Description string `json:"Description"`
	//BelongArea int64 `json:"belong_area"`//所属库房
	//HashCode string `json:"hash_code"`//为了让管理人员不作弊的校验码,但实际上如果删库就会没有意义，除非与员工出借记录分开管理。所以还是得用区块链保证无法作弊。
	//
	ID           int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID"`
	PID          int64  `protobuf:"varint,2,opt,name=PID,proto3" json:"PID"`
	WID          int64  `protobuf:"varint,3,opt,name=WID,proto3" json:"WID"`
	BorrowTime   int64  `protobuf:"varint,4,opt,name=BorrowTime,proto3" json:"BorrowTime"`
	ScheduleTime int64  `protobuf:"varint,5,opt,name=ScheduleTime,proto3" json:"ScheduleTime"`
	ReturnTime   int64  `protobuf:"varint,6,opt,name=ReturnTime,proto3" json:"ReturnTime"`
	Description  string `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description"`
	BelongArea   int64  `protobuf:"varint,8,opt,name=BelongArea,proto3" json:"BelongArea"`
	Hash         []byte `protobuf:"bytes,9,opt,name=Hash,proto3" json:"Hash"`
	PreHash      []byte `protobuf:"bytes,10,opt,name=PreHash,proto3" json:"PreHash"`
}

func (x *Borrowlog_Response) Reset() {
	*x = Borrowlog_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrowlog_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrowlog_Response) ProtoMessage() {}

func (x *Borrowlog_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrowlog_Response.ProtoReflect.Descriptor instead.
func (*Borrowlog_Response) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{5}
}

func (x *Borrowlog_Response) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Borrowlog_Response) GetPID() int64 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Borrowlog_Response) GetWID() int64 {
	if x != nil {
		return x.WID
	}
	return 0
}

func (x *Borrowlog_Response) GetBorrowTime() int64 {
	if x != nil {
		return x.BorrowTime
	}
	return 0
}

func (x *Borrowlog_Response) GetScheduleTime() int64 {
	if x != nil {
		return x.ScheduleTime
	}
	return 0
}

func (x *Borrowlog_Response) GetReturnTime() int64 {
	if x != nil {
		return x.ReturnTime
	}
	return 0
}

func (x *Borrowlog_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Borrowlog_Response) GetBelongArea() int64 {
	if x != nil {
		return x.BelongArea
	}
	return 0
}

func (x *Borrowlog_Response) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Borrowlog_Response) GetPreHash() []byte {
	if x != nil {
		return x.PreHash
	}
	return nil
}

type Borrowlogs_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*Borrowlog_Response `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs"`
}

func (x *Borrowlogs_Response) Reset() {
	*x = Borrowlogs_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrowlogs_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrowlogs_Response) ProtoMessage() {}

func (x *Borrowlogs_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrowlogs_Response.ProtoReflect.Descriptor instead.
func (*Borrowlogs_Response) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{6}
}

func (x *Borrowlogs_Response) GetLogs() []*Borrowlog_Response {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Returns_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *Returns_Request) Reset() {
	*x = Returns_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Returns_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Returns_Request) ProtoMessage() {}

func (x *Returns_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Returns_Request.ProtoReflect.Descriptor instead.
func (*Returns_Request) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{7}
}

func (x *Returns_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ToOtherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`   //物品已有记录
	Wid int64 `protobuf:"varint,2,opt,name=wid,proto3" json:"wid"` //其它人的id，方便变更
}

func (x *ToOtherRequest) Reset() {
	*x = ToOtherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToOtherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToOtherRequest) ProtoMessage() {}

func (x *ToOtherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToOtherRequest.ProtoReflect.Descriptor instead.
func (*ToOtherRequest) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{8}
}

func (x *ToOtherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToOtherRequest) GetWid() int64 {
	if x != nil {
		return x.Wid
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response_HashTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *Response_HashTest) Reset() {
	*x = Response_HashTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_borrow_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_HashTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_HashTest) ProtoMessage() {}

func (x *Response_HashTest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_borrow_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_HashTest.ProtoReflect.Descriptor instead.
func (*Response_HashTest) Descriptor() ([]byte, []int) {
	return file_proto_borrow_proto_rawDescGZIP(), []int{10}
}

func (x *Response_HashTest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_borrow_proto protoreflect.FileDescriptor

var file_proto_borrow_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x22, 0xd5, 0x01, 0x0a,
	0x0e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x0a, 0x49, 0x44, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0b, 0x57, 0x49, 0x44, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x57, 0x49, 0x44, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x49, 0x44, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x50, 0x49, 0x44, 0x22, 0x9c, 0x02, 0x0a, 0x12, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x6c,
	0x6f, 0x67, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x50,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x57, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x57, 0x49, 0x44, 0x12,
	0x1e, 0x0a, 0x0a, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x41,
	0x72, 0x65, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x42, 0x65, 0x6c, 0x6f, 0x6e,
	0x67, 0x41, 0x72, 0x65, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x72, 0x65, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x45, 0x0a, 0x13, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x6c, 0x6f, 0x67,
	0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x6f,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x6c, 0x6f, 0x67, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x21, 0x0a, 0x0f, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a,
	0x10, 0x74, 0x6f, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x77, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x48, 0x61,
	0x73, 0x68, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xb0, 0x04, 0x0a, 0x06, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x12, 0x32, 0x0a, 0x06, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x2e, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12,
	0x17, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73,
	0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x54, 0x6f,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x74,
	0x6f, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x12, 0x18, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x74, 0x6f, 0x5f, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a,
	0x0d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x12, 0x14,
	0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x12, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x49, 0x44, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x6c, 0x6f, 0x67, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x42, 0x79, 0x57, 0x49, 0x44, 0x12, 0x13, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e,
	0x57, 0x49, 0x44, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x6c, 0x6f, 0x67, 0x73, 0x5f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x42, 0x79, 0x50, 0x49, 0x44, 0x12, 0x13, 0x2e, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x2e, 0x50, 0x49, 0x44, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x07, 0x54, 0x65, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x48, 0x61, 0x73, 0x68, 0x54, 0x65, 0x73, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_borrow_proto_rawDescOnce sync.Once
	file_proto_borrow_proto_rawDescData = file_proto_borrow_proto_rawDesc
)

func file_proto_borrow_proto_rawDescGZIP() []byte {
	file_proto_borrow_proto_rawDescOnce.Do(func() {
		file_proto_borrow_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_borrow_proto_rawDescData)
	})
	return file_proto_borrow_proto_rawDescData
}

var file_proto_borrow_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_borrow_proto_goTypes = []interface{}{
	(*Borrow_Request)(nil),      // 0: borrow.Borrow_Request
	(*Null_Request)(nil),        // 1: borrow.Null_Request
	(*ID_Request)(nil),          // 2: borrow.ID_Request
	(*WID_Request)(nil),         // 3: borrow.WID_Request
	(*PID_Request)(nil),         // 4: borrow.PID_Request
	(*Borrowlog_Response)(nil),  // 5: borrow.Borrowlog_Response
	(*Borrowlogs_Response)(nil), // 6: borrow.Borrowlogs_Response
	(*Returns_Request)(nil),     // 7: borrow.Returns_Request
	(*ToOtherRequest)(nil),      // 8: borrow.to_other_request
	(*Response)(nil),            // 9: borrow.Response
	(*Response_HashTest)(nil),   // 10: borrow.Response_HashTest
}
var file_proto_borrow_proto_depIdxs = []int32{
	5,  // 0: borrow.Borrowlogs_Response.logs:type_name -> borrow.Borrowlog_Response
	0,  // 1: borrow.Borrow.Borrow:input_type -> borrow.Borrow_Request
	7,  // 2: borrow.Borrow.Return:input_type -> borrow.Returns_Request
	8,  // 3: borrow.Borrow.ToOther:input_type -> borrow.to_other_request
	8,  // 4: borrow.Borrow.CheckToOther:input_type -> borrow.to_other_request
	1,  // 5: borrow.Borrow.FindBorrowAll:input_type -> borrow.Null_Request
	2,  // 6: borrow.Borrow.FindBorrowByID:input_type -> borrow.ID_Request
	3,  // 7: borrow.Borrow.FindBorrowByWID:input_type -> borrow.WID_Request
	4,  // 8: borrow.Borrow.FindBorrowByPID:input_type -> borrow.PID_Request
	1,  // 9: borrow.Borrow.TestLog:input_type -> borrow.Null_Request
	9,  // 10: borrow.Borrow.Borrow:output_type -> borrow.Response
	9,  // 11: borrow.Borrow.Return:output_type -> borrow.Response
	9,  // 12: borrow.Borrow.ToOther:output_type -> borrow.Response
	9,  // 13: borrow.Borrow.CheckToOther:output_type -> borrow.Response
	6,  // 14: borrow.Borrow.FindBorrowAll:output_type -> borrow.Borrowlogs_Response
	5,  // 15: borrow.Borrow.FindBorrowByID:output_type -> borrow.Borrowlog_Response
	6,  // 16: borrow.Borrow.FindBorrowByWID:output_type -> borrow.Borrowlogs_Response
	6,  // 17: borrow.Borrow.FindBorrowByPID:output_type -> borrow.Borrowlogs_Response
	10, // 18: borrow.Borrow.TestLog:output_type -> borrow.Response_HashTest
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_borrow_proto_init() }
func file_proto_borrow_proto_init() {
	if File_proto_borrow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_borrow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Borrow_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PID_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Borrowlog_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Borrowlogs_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Returns_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToOtherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_borrow_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_HashTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_borrow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_borrow_proto_goTypes,
		DependencyIndexes: file_proto_borrow_proto_depIdxs,
		MessageInfos:      file_proto_borrow_proto_msgTypes,
	}.Build()
	File_proto_borrow_proto = out.File
	file_proto_borrow_proto_rawDesc = nil
	file_proto_borrow_proto_goTypes = nil
	file_proto_borrow_proto_depIdxs = nil
}
